AIRPORT_CODES = {
    # --- GLOBAL CITIES ---
    "new york": "JFK",
    "los angeles": "LAX",
    "chicago": "ORD",
    "atlanta": "ATL",
    "dallas": "DFW",
    "denver": "DEN",
    "san francisco": "SFO",
    "seattle": "SEA",
    "las vegas": "LAS",
    "orlando": "MCO",
    "miami": "MIA",
    "houston": "IAH",
    "phoenix": "PHX",
    "boston": "BOS",
    "minneapolis": "MSP",
    "detroit": "DTW",
    "philadelphia": "PHL",
    "toronto": "YYZ",
    "vancouver": "YVR",
    "washington": "IAD",
    "bali": "DPS",
    # --- INDIA ---
    "mumbai": "BOM",
    "delhi": "DEL",
    "bangalore": "BLR",
    "pune": "PNQ",
    "hyderabad": "HYD",
    "chennai": "MAA",
    "kolkata": "CCU",
    "ahmedabad": "AMD",
    "kochi": "COK",
    "goa": "GOI",
    "amritsar": "ATQ",
    "lucknow": "LKO",
    "jaipur": "JAI",
    "guwahati": "GAU",
    "thiruvananthapuram": "TRV",
    "bhubaneswar": "BBI",
    "coimbatore": "CJB",
    "indore": "IDR",
    "nagpur": "NAG",
    "patna": "PAT",
    # --- MIDDLE EAST ---
    "dubai": "DXB",
    "abu dhabi": "AUH",
    "sharjah": "SHJ",
    "doha": "DOH",
    "riyadh": "RUH",
    "jeddah": "JED",
    "muscat": "MCT",
    "bahrain": "BAH",
    "kuwait": "KWI",
    "tel aviv": "TLV",
    "istanbul": "IST",
    # --- EUROPE & UNITED KINGDOM ---
    "london": "LHR",
    "birmingham": "BHX",
    "manchester": "MAN",
    "edinburgh": "EDI",
    "glasgow": "GLA",
    "paris": "CDG",
    "frankfurt": "FRA",
    "amsterdam": "AMS",
    "munich": "MUC",
    "rome": "FCO",
    "madrid": "MAD",
    "barcelona": "BCN",
    "zurich": "ZRH",
    "vienna": "VIE",
    "brussels": "BRU",
    "copenhagen": "CPH",
    "stockholm": "ARN",
    "oslo": "OSL",
    "helsinki": "HEL",
    "dublin": "DUB",
    "lisbon": "LIS",
    "athens": "ATH",
    "milan": "MXP",
    "geneva": "GVA",
    # --- NORTH AMERICA (USA & CANADA) ---
    "new york": "JFK",
    "los angeles": "LAX",
    "chicago": "ORD",
    "atlanta": "ATL",
    "dallas": "DFW",
    "denver": "DEN",
    "san francisco": "SFO",
    "seattle": "SEA",
    "las vegas": "LAS",
    "orlando": "MCO",
    "miami": "MIA",
    "houston": "IAH",
    "phoenix": "PHX",
    "boston": "BOS",
    "minneapolis": "MSP",
    "detroit": "DTW",
    "philadelphia": "PHL",
    "toronto": "YYZ",
    "vancouver": "YVR",
    "montreal": "YUL",
    "calgary": "YYC",
    # --- ASIA-PACIFIC ---
    "singapore": "SIN",
    "bangkok": "BKK",
    "kuala lumpur": "KUL",
    "jakarta": "CGK",
    "manila": "MNL",
    "tokyo": "HND",
    "osaka": "KIX",
    "seoul": "ICN",
    "hong kong": "HKG",
    "taipei": "TPE",
    "shanghai": "PVG",
    "beijing": "PEK",
    "guangzhou": "CAN",
    "sydney": "SYD",
    "melbourne": "MEL",
    "brisbane": "BNE",
    "auckland": "AKL",
    "colombo": "CMB",
    "dhaka": "DAC",
    "kathmandu": "KTM",
    "male": "MLE",
    # --- AFRICA & SOUTH AMERICA ---
    "johannesburg": "JNB",
    "cairo": "CAI",
    "nairobi": "NBO",
    "addis ababa": "ADD",
    "cape town": "CPT",
    "casablanca": "CMN",
    "sao paulo": "GRU",
    "rio de janeiro": "GIG",
    "buenos aires": "EZE",
    "bogota": "BOG",
    "lima": "LIM",
    "santiago": "SCL",
}
